name: Bug report
description: Report a reproducible bug in Tabbed Terminal
title: "bug: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting. Please provide enough detail to reproduce the issue.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Include exact steps, shortcuts, and pane/workspace context.
      placeholder: |
        1. Open app
        2. Create Pane 2
        3. Press Cmd+...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshot / log (optional)
      description: Paste screenshots, terminal output, or stack traces.
  - type: input
    id: version
    attributes:
      label: App version (or commit)
      placeholder: v0.2.0 / 1171160
  - type: dropdown
    id: os
    attributes:
      label: OS
      options:
        - macOS
        - Windows
        - Linux
        - Other
